//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSEWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public int HostID { get; set; }
        public int FollowerID { get; set; }
        public int C_id { get; set; }
    }
}
