//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSEWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuseSQLEntities : DbContext
    {
        public MuseSQLEntities()
            : base("name=MuseSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Follow> Follow { get; set; }
        public DbSet<Music> Music { get; set; }
        public DbSet<Timeline> Timeline { get; set; }
        public DbSet<User> User { get; set; }
    }
}
