//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSEWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int MusicID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Ratings { get; set; }
        public string Last_Played { get; set; }
        public Nullable<int> Count { get; set; }
        public string Data { get; set; }
        public string Artist { get; set; }
        public string Album { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
    }
}
